// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api_key/{id}": {
            "get": {
                "description": "Retrieve API key by UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api_key"
                ],
                "summary": "Get API key by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ApiKey ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ApiKey"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/complaint": {
            "get": {
                "description": "List all complaints (requires auth)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "complaint"
                ],
                "summary": "List complaints",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Complaint"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a complaint (public endpoint using API Key)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "complaint"
                ],
                "summary": "Create a complaint",
                "parameters": [
                    {
                        "description": "Complaint data",
                        "name": "complaint",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateComplaintDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Complaint"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/complaint/code/{code}": {
            "get": {
                "description": "Retrieve a complaint using public code (API Key required)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "complaint"
                ],
                "summary": "Get complaint by public code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Public code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Complaint"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/complaint/{id}": {
            "get": {
                "description": "Retrieve complaint by UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "complaint"
                ],
                "summary": "Get complaint by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Complaint ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Complaint"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/complaint/{id}/action": {
            "post": {
                "description": "Update complaint status or details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "complaint"
                ],
                "summary": "Update complaint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Complaint ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update data",
                        "name": "complaint",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateComplaintDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Complaint"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/location/{id}": {
            "get": {
                "description": "Retrieve location by UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "location"
                ],
                "summary": "Get location by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Location ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Location"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/report/summary": {
            "get": {
                "description": "Returns summary report data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "report"
                ],
                "summary": "Get summary report",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SummaryReport"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/role": {
            "post": {
                "description": "Create role",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "Create a role for a tenant",
                "parameters": [
                    {
                        "description": "Role data",
                        "name": "role",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateRoleDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Role"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/role/{id}": {
            "get": {
                "description": "Retrieve role by UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "Get role by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Role ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Role"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tenant": {
            "get": {
                "description": "Get all tenants",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tenant"
                ],
                "summary": "List tenants",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Tenant"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create tenant with the provided data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tenant"
                ],
                "summary": "Create a new tenant",
                "parameters": [
                    {
                        "description": "Tenant data",
                        "name": "tenant",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateTenantDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Tenant"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tenant/{id}": {
            "get": {
                "description": "Get a tenant using its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tenant"
                ],
                "summary": "Get tenant by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Tenant"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "description": "Update tenant fields (activate tenant etc.)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tenant"
                ],
                "summary": "Update tenant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Tenant update data",
                        "name": "tenant",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateTenantDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Tenant"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tenant/{id}/api-keys": {
            "post": {
                "description": "Create an API key for a specific tenant",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api_key"
                ],
                "summary": "Create API Key for tenant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "API Key data",
                        "name": "apiKey",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateApiKeyDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.ApiKey"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tenant/{id}/location": {
            "post": {
                "description": "Create location under a tenant",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "location"
                ],
                "summary": "Create a location for a tenant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "9Location data",
                        "name": "location",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateLocationDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Location"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tenant/{id}/locations": {
            "get": {
                "description": "Retrieve all locations under a tenant",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "location"
                ],
                "summary": "Get locations by tenant ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Location"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user": {
            "post": {
                "description": "Create a new user for a tenant",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Create a user",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateUserDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "Authenticate user and return tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user/{id}": {
            "get": {
                "description": "Retrieve user by UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AuthRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.AuthResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "dto.CreateApiKeyDTO": {
            "type": "object",
            "required": [
                "api_key",
                "location_id",
                "scope",
                "tenant_id"
            ],
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "location_id": {
                    "type": "string"
                },
                "scope": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                }
            }
        },
        "dto.CreateComplaintDTO": {
            "type": "object",
            "required": [
                "category_id",
                "description",
                "location_id",
                "source",
                "status",
                "tenant_id",
                "type"
            ],
            "properties": {
                "api_key_id": {
                    "type": "string"
                },
                "category_id": {
                    "type": "string"
                },
                "code_public": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "is_closed": {
                    "type": "boolean"
                },
                "location_id": {
                    "type": "string"
                },
                "requested_action": {
                    "type": "string"
                },
                "source": {
                    "type": "string",
                    "enum": [
                        "WEB",
                        "OFICINA",
                        "API",
                        "CALL"
                    ]
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "RECIBIDO",
                        "EVALUACION",
                        "PROCESO",
                        "ATENDIDO",
                        "CERRADO"
                    ]
                },
                "tenant_id": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "QUEJA",
                        "RECLAMO"
                    ]
                }
            }
        },
        "dto.CreateLocationDTO": {
            "type": "object",
            "required": [
                "address",
                "department",
                "district",
                "name",
                "province",
                "public_code",
                "tenant_id",
                "type"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 5
                },
                "department": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                },
                "postal_code": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                },
                "public_code": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "tenant_id": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "FISICO",
                        "ONLINE",
                        "AMBOS"
                    ]
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "dto.CreateRoleDTO": {
            "type": "object",
            "required": [
                "name",
                "tenant_id"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "is_system": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                }
            }
        },
        "dto.CreateTenantDTO": {
            "type": "object",
            "required": [
                "email_contact",
                "name",
                "phone_contact",
                "ruc"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "country": {
                    "description": "País - valores permitidos: \"Perú\", \"España\", \"Colombia\", \"Chile\"",
                    "type": "string",
                    "enum": [
                        "Perú",
                        "España",
                        "Colombia",
                        "Chile"
                    ]
                },
                "department": {
                    "description": "Dirección y branding",
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "email_contact": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "logo_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone_contact": {
                    "type": "string"
                },
                "postal_code": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                },
                "ruc": {
                    "type": "string"
                }
            }
        },
        "dto.CreateUserDTO": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "full_name",
                "last_name",
                "location_id",
                "password",
                "role_id",
                "tenant_id",
                "user_name"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                },
                "full_name": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 2
                },
                "is_active": {
                    "type": "boolean"
                },
                "last_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                },
                "location_id": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 8
                },
                "phone": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 7
                },
                "role_id": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 5
                }
            }
        },
        "dto.UpdateComplaintDTO": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "new_status": {
                    "description": "new_status permite cambiar status sin respuesta",
                    "type": "string"
                },
                "responder_id": {
                    "type": "string"
                },
                "response_status": {
                    "description": "DRAFT o SENT",
                    "type": "string"
                },
                "response_text": {
                    "description": "Respuesta del sistema",
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "RECIBIDO",
                        "EN EVALUACION",
                        "PROCESO",
                        "ATENDIDO",
                        "CERRADO"
                    ]
                }
            }
        },
        "dto.UpdateTenantDTO": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "country": {
                    "description": "País opcional",
                    "type": "string",
                    "enum": [
                        "Perú",
                        "España",
                        "Colombia",
                        "Chile"
                    ]
                },
                "department": {
                    "description": "Dirección y branding opcionales",
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "email_contact": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_confirm": {
                    "type": "boolean"
                },
                "logo_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone_contact": {
                    "type": "string"
                },
                "postal_code": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                },
                "ruc": {
                    "type": "string"
                }
            }
        },
        "model.ApiKey": {
            "type": "object",
            "properties": {
                "apiKey": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "locationID": {
                    "type": "string"
                },
                "scope": {
                    "type": "string"
                },
                "tenantID": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.Complaint": {
            "type": "object",
            "properties": {
                "apiKeyID": {
                    "type": "string"
                },
                "categoryID": {
                    "type": "string"
                },
                "codePublic": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isClosed": {
                    "type": "boolean"
                },
                "locationID": {
                    "type": "string"
                },
                "requestedAction": {
                    "type": "string"
                },
                "resolvedAt": {
                    "type": "string"
                },
                "responderID": {
                    "type": "string"
                },
                "responseSentAt": {
                    "type": "string"
                },
                "responseStatus": {
                    "$ref": "#/definitions/model.ResponseStatus"
                },
                "responseText": {
                    "description": "Campos de respuesta gestionados por usuarios del sistema",
                    "type": "string"
                },
                "source": {
                    "$ref": "#/definitions/model.ComplaintSource"
                },
                "status": {
                    "$ref": "#/definitions/model.ComplaintStatus"
                },
                "tenantID": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/model.ComplaintType"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.ComplaintSource": {
            "type": "string",
            "enum": [
                "WEB PUBLICA",
                "OFICINA FISICA",
                "API",
                "CALL CENTER"
            ],
            "x-enum-varnames": [
                "WEB",
                "OFICINA",
                "API",
                "CALL"
            ]
        },
        "model.ComplaintStatus": {
            "type": "string",
            "enum": [
                "RECIBIDO",
                "EN EVALUACION",
                "EN PROCESO",
                "ATENDIDO",
                "CERRADO"
            ],
            "x-enum-varnames": [
                "RECIBIDO",
                "EVALUACION",
                "PROCESO",
                "ATENDIDO",
                "CERRADO"
            ]
        },
        "model.ComplaintType": {
            "type": "string",
            "enum": [
                "RECLAMO",
                "QUEJA"
            ],
            "x-enum-varnames": [
                "RECLAMO",
                "QUEJA"
            ]
        },
        "model.Country": {
            "type": "string",
            "enum": [
                "Perú",
                "España",
                "Colombia",
                "Chile"
            ],
            "x-enum-varnames": [
                "CountryPeru",
                "CountryEspana",
                "CountryColombia",
                "CountryChile"
            ]
        },
        "model.EstablishmentType": {
            "type": "string",
            "enum": [
                "FISICO",
                "ONLINE",
                "AMBOS"
            ],
            "x-enum-varnames": [
                "EstablishmentPhysical",
                "EstablishmentOnline",
                "EstablishmentBoth"
            ]
        },
        "model.Location": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "department": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "postalCode": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                },
                "publicCode": {
                    "type": "string"
                },
                "tenantID": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/model.EstablishmentType"
                },
                "updatedAt": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "model.ResponseStatus": {
            "type": "string",
            "enum": [
                "DRAFT",
                "SENT"
            ],
            "x-enum-varnames": [
                "RESPONSE_DRAFT",
                "RESPONSE_SENT"
            ]
        },
        "model.Role": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isSystem": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "tenantID": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.SummaryReport": {
            "type": "object",
            "properties": {
                "pending": {
                    "type": "integer"
                },
                "resolved": {
                    "type": "integer"
                },
                "slaCompliance": {
                    "type": "string"
                },
                "totalComplaints": {
                    "type": "integer"
                }
            }
        },
        "model.Tenant": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "Dirección detallada",
                    "type": "string"
                },
                "country": {
                    "description": "País",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.Country"
                        }
                    ]
                },
                "createdAt": {
                    "type": "string"
                },
                "department": {
                    "description": "Nuevos campos para dirección y branding",
                    "type": "string"
                },
                "district": {
                    "description": "Distrito",
                    "type": "string"
                },
                "emailContact": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "isConfirm": {
                    "type": "boolean"
                },
                "logoURL": {
                    "description": "URL del logo (opcional)",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phoneContact": {
                    "type": "string"
                },
                "postalCode": {
                    "description": "Código postal (opcional)",
                    "type": "string"
                },
                "province": {
                    "description": "Provincia",
                    "type": "string"
                },
                "ruc": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "lastName": {
                    "type": "string"
                },
                "locationID": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "roleID": {
                    "type": "string"
                },
                "roleName": {
                    "type": "string"
                },
                "tenantID": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Book Claims API",
	Description:      "API para gestión de reclamos multi-tenant",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
